// Mock data for Phase 1 development. Replace with Supabase queries in later phases.

export const PIPELINE_STAGES = [
  { id: 'new_lead', label: 'Novo Lead' },
  { id: 'contacted', label: 'Contatado' },
  { id: 'in_progress', label: 'Em Andamento' },
  { id: 'negotiating', label: 'Negociando' },
  { id: 'closed', label: 'Fechado' },
]

export const mockLeads = [
  {
    id: 'l1',
    nombre: 'Nova Dynamics',
    contacto: 'Alex Rivera',
    valor_estimado: 45000,
    canal_origen: 'instagram',
    pipeline_stage: 'new_lead',
    avatar: 'https://i.pravatar.cc/64?img=12',
    actualizado_en: '2026-04-23T10:00:00Z',
    badge: 'Novo',
  },
  {
    id: 'l2',
    nombre: 'Apex Industries',
    contacto: 'Marta Silva',
    valor_estimado: 12500,
    canal_origen: 'whatsapp',
    pipeline_stage: 'new_lead',
    avatar: 'https://i.pravatar.cc/64?img=32',
    actualizado_en: '2026-04-22T14:00:00Z',
    badge: 'Entrada',
  },
  {
    id: 'l3',
    nombre: 'Horizon Ventures',
    contacto: 'Diego López',
    valor_estimado: 85000,
    canal_origen: 'tiktok',
    pipeline_stage: 'contacted',
    avatar: 'https://i.pravatar.cc/64?img=15',
    actualizado_en: '2026-04-21T08:30:00Z',
    badge: 'Acompanhamento',
  },
  {
    id: 'l4',
    nombre: 'Quantum Tech',
    contacto: 'Sarah Jenkins',
    valor_estimado: 120000,
    canal_origen: 'instagram',
    pipeline_stage: 'in_progress',
    avatar: 'https://i.pravatar.cc/64?img=47',
    actualizado_en: '2026-04-20T11:00:00Z',
    badge: 'Quente',
  },
  {
    id: 'l5',
    nombre: 'Synergy Group',
    contacto: 'Marcus Vance',
    valor_estimado: 34000,
    canal_origen: 'whatsapp',
    pipeline_stage: 'in_progress',
    avatar: 'https://i.pravatar.cc/64?img=68',
    actualizado_en: '2026-04-19T16:00:00Z',
    badge: 'Proposta',
  },
  {
    id: 'l6',
    nombre: 'Stellar Logistics',
    contacto: 'Elena Romero',
    valor_estimado: 95000,
    canal_origen: 'instagram',
    pipeline_stage: 'negotiating',
    avatar: 'https://i.pravatar.cc/64?img=24',
    actualizado_en: '2026-04-18T09:00:00Z',
    badge: 'Contrato',
  },
  {
    id: 'l7',
    nombre: 'Nova Corp',
    contacto: 'Chloe Zhang',
    valor_estimado: 55000,
    canal_origen: 'tiktok',
    pipeline_stage: 'closed',
    avatar: 'https://i.pravatar.cc/64?img=44',
    actualizado_en: '2026-04-17T12:30:00Z',
    badge: 'Ganho',
  },
]

export const mockConversations = [
  {
    id: 'c1',
    lead_id: 'l4',
    lead_name: 'Sarah Jenkins',
    lead_avatar: 'https://i.pravatar.cc/64?img=47',
    cargo: 'VP of Operations',
    empresa: 'NovaCorp',
    canal: 'instagram',
    last_message: 'That timeline works perfectly for us. Can you send the updated proposal?',
    last_time: '2026-04-25T14:32:00Z',
    unread: 3,
    online: true,
    modo: 'humano',
    stage: 'Negociação',
    valor_estimado: 125000,
    email: 'sarah@novacorp.com',
    telefone: '+1 (559) 356-1824',
    fonte: 'Inbound / Webinar',
    timezone: 'San Francisco, CA (PST)',
    tags: ['Enterprise', 'Q2 Target', 'High Value'],
  },
  {
    id: 'c2',
    lead_id: 'l3',
    lead_name: 'Marcus Vance',
    lead_avatar: 'https://i.pravatar.cc/64?img=68',
    cargo: 'CEO',
    empresa: 'Horizon Ventures',
    canal: 'whatsapp',
    last_message: 'Could we schedule a quick demo for my engineering team?',
    last_time: '2026-04-25T11:10:00Z',
    unread: 1,
    online: false,
    modo: 'bot',
    stage: 'Contatado',
    valor_estimado: 85000,
    email: 'marcus@horizonventures.com',
    telefone: '+1 (415) 222-9900',
    fonte: 'Instagram',
    timezone: 'New York, NY (EST)',
    tags: ['SaaS', 'Demo pendente'],
  },
  {
    id: 'c3',
    lead_id: 'l5',
    lead_name: 'Chloe Zhang',
    lead_avatar: 'https://i.pravatar.cc/64?img=44',
    cargo: 'Marketing Director',
    empresa: 'Synergy Group',
    canal: 'tiktok',
    last_message: 'I\'m putting together the custom proposal based on the tier we discussed.',
    last_time: '2026-04-24T17:45:00Z',
    unread: 0,
    online: true,
    modo: 'bot',
    stage: 'Em Andamento',
    valor_estimado: 34000,
    email: 'chloe@synergy.com',
    telefone: '+1 (213) 777-4455',
    fonte: 'TikTok',
    timezone: 'Los Angeles, CA (PST)',
    tags: ['SMB', 'Proposta'],
  },
  {
    id: 'c4',
    lead_id: 'l1',
    lead_name: 'Alex Rivera',
    lead_avatar: 'https://i.pravatar.cc/64?img=12',
    cargo: 'Founder',
    empresa: 'Nova Dynamics',
    canal: 'whatsapp',
    last_message: 'Hi, thanks for the info. Looking forward to next steps!',
    last_time: '2026-04-24T09:20:00Z',
    unread: 0,
    online: false,
    modo: 'bot',
    stage: 'Novo Lead',
    valor_estimado: 45000,
    email: 'alex@novadynamics.com',
    telefone: '+1 (310) 888-2200',
    fonte: 'Instagram',
    timezone: 'Miami, FL (EST)',
    tags: ['Novo'],
  },
]

export const mockMessages = {
  c1: [
    {
      id: 'm1',
      contenido: 'Hi Alex, thanks for the call earlier. Can you send the proposal once more? I\'d like to review the timeline again.',
      direccion: 'entrante',
      tipo: 'texto',
      enviado_en: '2026-04-25T13:00:00Z',
    },
    {
      id: 'm2',
      contenido: 'Claro! Aqui está o documento atualizado com o cronograma revisado e os módulos detalhados.',
      direccion: 'saliente',
      tipo: 'texto',
      enviado_en: '2026-04-25T13:05:00Z',
    },
    {
      id: 'm3',
      contenido: 'Design_Requirements_v2.pdf',
      direccion: 'saliente',
      tipo: 'arquivo',
      enviado_en: '2026-04-25T13:06:00Z',
      file_size: '2.4 MB',
    },
    {
      id: 'm4',
      contenido: 'Good to see it. Is it usually like this for other clients as well? Should I expect the same timeline?',
      direccion: 'entrante',
      tipo: 'texto',
      enviado_en: '2026-04-25T13:20:00Z',
    },
    {
      id: 'm5',
      contenido: 'I\'m putting together the custom proposal based on the tier we discussed. Should have it ready by tomorrow.',
      direccion: 'saliente',
      tipo: 'texto',
      enviado_en: '2026-04-25T13:45:00Z',
    },
    {
      id: 'm6',
      contenido: 'That timeline works perfectly for us. Can you send the updated proposal?',
      direccion: 'entrante',
      tipo: 'texto',
      enviado_en: '2026-04-25T14:32:00Z',
    },
  ],
  c2: [
    {
      id: 'm7',
      contenido: 'Olá Marcus! Obrigado pelo seu interesse na Agenda Cheia.',
      direccion: 'saliente',
      tipo: 'texto',
      enviado_en: '2026-04-25T10:00:00Z',
    },
    {
      id: 'm8',
      contenido: 'Could we schedule a quick demo for my engineering team?',
      direccion: 'entrante',
      tipo: 'texto',
      enviado_en: '2026-04-25T11:10:00Z',
    },
  ],
  c3: [
    {
      id: 'm9',
      contenido: 'I\'m putting together the custom proposal based on the tier we discussed.',
      direccion: 'saliente',
      tipo: 'texto',
      enviado_en: '2026-04-24T17:45:00Z',
    },
  ],
  c4: [
    {
      id: 'm10',
      contenido: 'Hi, thanks for the info. Looking forward to next steps!',
      direccion: 'entrante',
      tipo: 'texto',
      enviado_en: '2026-04-24T09:20:00Z',
    },
  ],
}

export const APPOINTMENT_TYPES = [
  { value: 'ligacao',  label: 'Ligação',    color: '#f5a623' },
  { value: 'demo',     label: 'Demo',       color: '#3498db' },
  { value: 'followup', label: 'Follow-up',  color: '#2ecc71' },
  { value: 'reuniao',  label: 'Reunião',    color: '#9b59b6' },
]

export const DURATIONS = [
  { value: 15, label: '15 min' },
  { value: 30, label: '30 min' },
  { value: 45, label: '45 min' },
  { value: 60, label: '1 hora' },
]

export const mockAppointments = [
  {
    id: 'a1',
    lead_id: 'l4',
    lead_name: 'Sarah Jenkins',
    lead_avatar: 'https://i.pravatar.cc/64?img=47',
    canal: 'instagram',
    titulo: 'Demo da plataforma',
    tipo: 'demo',
    descricao: 'Apresentação completa do módulo de automação.',
    inicio: '2026-04-25T10:00:00',
    fim:    '2026-04-25T11:00:00',
    duracao: 60,
    status: 'programada',
    criado_por: 'humano',
    google_sync: true,
  },
  {
    id: 'a2',
    lead_id: 'l3',
    lead_name: 'Marcus Vance',
    lead_avatar: 'https://i.pravatar.cc/64?img=68',
    canal: 'whatsapp',
    titulo: 'Ligação de qualificação',
    tipo: 'ligacao',
    descricao: 'Descoberta das necessidades do cliente.',
    inicio: '2026-04-25T14:30:00',
    fim:    '2026-04-25T15:00:00',
    duracao: 30,
    status: 'programada',
    criado_por: 'bot',
    google_sync: false,
  },
  {
    id: 'a3',
    lead_id: 'l5',
    lead_name: 'Chloe Zhang',
    lead_avatar: 'https://i.pravatar.cc/64?img=44',
    canal: 'tiktok',
    titulo: 'Follow-up proposta',
    tipo: 'followup',
    descricao: 'Revisar proposta enviada e tirar dúvidas.',
    inicio: '2026-04-28T09:00:00',
    fim:    '2026-04-28T09:30:00',
    duracao: 30,
    status: 'programada',
    criado_por: 'humano',
    google_sync: false,
  },
  {
    id: 'a4',
    lead_id: 'l6',
    lead_name: 'Elena Romero',
    lead_avatar: 'https://i.pravatar.cc/64?img=24',
    canal: 'instagram',
    titulo: 'Reunião de contrato',
    tipo: 'reuniao',
    descricao: 'Revisão final dos termos e assinatura.',
    inicio: '2026-04-29T15:00:00',
    fim:    '2026-04-29T16:00:00',
    duracao: 60,
    status: 'programada',
    criado_por: 'humano',
    google_sync: true,
  },
  {
    id: 'a5',
    lead_id: 'l1',
    lead_name: 'Alex Rivera',
    lead_avatar: 'https://i.pravatar.cc/64?img=12',
    canal: 'whatsapp',
    titulo: 'Ligação de boas-vindas',
    tipo: 'ligacao',
    descricao: 'Primeiro contato e apresentação.',
    inicio: '2026-04-26T11:00:00',
    fim:    '2026-04-26T11:15:00',
    duracao: 15,
    status: 'programada',
    criado_por: 'bot',
    google_sync: false,
  },
]

export const channelMeta = {
  instagram: { label: 'Instagram', color: 'var(--color-instagram)' },
  whatsapp: { label: 'WhatsApp', color: 'var(--color-whatsapp)' },
  tiktok: { label: 'TikTok', color: 'var(--color-tiktok-accent)' },
  youtube: { label: 'YouTube', color: 'var(--color-youtube)' },
  googleAds: { label: 'Google Ads', color: 'var(--color-google-ads)' },
  email: { label: 'E-mail', color: 'var(--color-email)' },
  manual: { label: 'Manual', color: 'var(--color-text-secondary)' },
}
